name: Setup
description: Perform standard setup and install dependencies using pnpm.

runs:
  using: composite
  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: "23"
        registry-url: 'https://registry.npmjs.org'

    - name: ⚙️ Enable Corepack
      shell: bash
      run: corepack enable

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
      env:
        HUSKY: "0"
